version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    image: frontend
    container_name: frontend_app
    depends_on:
      - mongodb
    ports:
      - "3001:3001"
  
  backend:
    image: backend
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL= "mongodb://mongodb:27017"

volumes:
  mongodb_data: